PUBLIC_HOSTNAME="3.140.246.5"

SHOPPING_PORT=7770
SHOPPING_ADMIN_PORT=7780
REDDIT_PORT=9999
GITLAB_PORT=8023
WIKIPEDIA_PORT=8888
MAP_PORT=3000
HOMEPAGE_PORT=4399

export SHOPPING="http://${PUBLIC_HOSTNAME}:${SHOPPING_PORT}"
export SHOPPING_ADMIN="http://${PUBLIC_HOSTNAME}:${SHOPPING_ADMIN_PORT}/admin"
export REDDIT="http://${PUBLIC_HOSTNAME}:${REDDIT_PORT}"
export GITLAB="http://${PUBLIC_HOSTNAME}:${GITLAB_PORT}"
export WIKIPEDIA="http://${PUBLIC_HOSTNAME}:${WIKIPEDIA_PORT}/wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing"
export MAP="http://${PUBLIC_HOSTNAME}:${MAP_PORT}"
export HOMEPAGE="http://${PUBLIC_HOSTNAME}:${HOMEPAGE_PORT}"
